### ISSUE TITLE
Tutorials 

### ISSUE THREAD

**Issue by ismaeljoseph** [AnaliaMok/TutsHub#1]
Good morning, 

Thank you for your contribution. It works well. But when i try to go on tutorial i have this errors : 
Base table or view not found: 1146 Table .

Will you help me fixe it? 
Also How can i add a contact page?

**Comment by analia-mok** [comment]
Hi @ismaeljoseph,

When it comes to creating any Page type, you can do so by logging into the admin, going to the Pages section found in the admin menu, and "add new". Plus, if you want this page to be navigable through a navigation menu, you can add a new link the "main" menu found in Voyager's menu builder. Technically, there should already be a Contact page in the system.

In terms of the error, however, 
1) Are these issues happening when going to Tutorials from the admin or from the front-end? 
2) Did you have any issues importing the database backup provided in the "backups" directory? Your error is due to the application reporting a database issue. 
3) If you see all of the tables in your database, ensure that the database credentials in your .env file are correct.
